# SPDX-FileCopyrightText: 2026 Mappalink
#
# SPDX-License-Identifier: MIT

services:
  omron-hd1500:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - ROBOT_ID=omron-hd1500
      - INORBIT_API_KEY=${INORBIT_API_KEY}
      - OMRON_ARCL_PASSWORD=${OMRON_ARCL_PASSWORD}
    volumes:
      - ../config:/config:ro
    restart: unless-stopped
